# Site settings
# in the templates available like {{ site.myvariable }}.
title: Porfolio técnico.
email: julioubedaquesada@gmail.com
brand: Julio Ubeda Quesada
headline: Científico de datos especialista en gestión pesquera
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: julioubedaquesada@gmail.com
phone: +34 000 000 000 

# Tracking
googleAnalitycsID: UA-83933844-1

